language: python
python: 3.6
sudo: false
addons:
  apt:
    sources:
      - elasticsearch-5.x
    packages:
    - elasticsearch
  postgresql: "9.5"
services:
  - elasticsearch
env:
  - TOX_ENV=py36
  - TOX_ENV=kinto-master
  - TOX_ENV=flake8
install: pip install -U tox
script: tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
